language: node_js
notifications:
  email: false

install:
- npm ci

jobs:
  include:
    - os: linux
      dist: bionic
      node_js: '12'
      addons:
        apt:
          packages:
          # These are required to run webkit
          - libwoff1
          - libopus0
          - libwebp6
          - libwebpdemux2
          - libenchant1c2a
          - libgudev-1.0-0
          - libsecret-1-0
          - libhyphen0
          - libgdk-pixbuf2.0-0
          - libegl1
          - libgles2
          - libevent-2.1-6
          - libnotify4
          - libxslt1.1
          - libvpx5
          # This is required to run chromium
          - libgbm1
          # this is needed for running headful tests
          - xvfb
      script:
        - npm run lint
        - xvfb-run --auto-servernum npm run ctest
        - xvfb-run --auto-servernum npm run ftest
        - xvfb-run --auto-servernum npm run wtest
    - os: osx
      osx_image: xcode11.3
      node_js: '12'
      script:
        - npm run lint
        - npm run ctest
        - npm run ftest
        - npm run wtest

