name: 'Upload blob report'
description: 'Upload blob report to GitHub artifacts (for pull requests)'
inputs:
  report_dir:
    description: 'Directory containing blob report'
    required: true
    type: string
    default: 'blob-report'
runs:
  using: "composite"
  steps:
    - name: Upload blob report to GitHub
      if: always() && github.event_name == 'pull_request'
      uses: actions/upload-artifact@v3
      with:
        name: all-blob-reports
        path: ${{ inputs.report_dir }}
        retention-days: 7
    - name: Write triggering pull request number in a file
      if: always() && github.event_name == 'pull_request'
      shell: bash
      run: echo '${{ github.event.number }}' > pull_request_number.txt;
    - name: Upload artifact with the pull request number
      if: always() && github.event_name == 'pull_request'
      uses: actions/upload-artifact@v3
      with:
        name: pull-request
        path: pull_request_number.txt
