apiVersion: apps/v1
kind: Deployment
metadata:
  name: grid-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grid
  template:
    metadata:
      labels:
        app: grid
    spec:
      containers:
      - name: grid
        image: playwright-grid
        resources:
          requests:
            cpu: "2"
            memory: "4Gi"
        imagePullPolicy: IfNotPresent
        env:
        - name: DEBUG
          value: "pw:grid*"
        - name: PLAYWRIGHT_GRID_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: access-key-secret
              key: access-key
        command: ["node", "./cli.js"]
        args: ["grid", "--port=3000"]

---
apiVersion: v1
kind: Service
metadata:
  name: grid-service
spec:
  selector:
    app: grid
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
