name: "tests Android"

on:
  push:
    branches:
      - main
      - release-*
  pull_request:
    branches:
      - main
      - release-*
    paths:
      - "**android**"
      - "utils/avd_*.js"
      - ".github/workflows/tests_android.yml"

env:
  # Force terminal colors. @see https://www.npmjs.com/package/colors
  FORCE_COLOR: 1
  FLAKINESS_CONNECTION_STRING: ${{ secrets.FLAKINESS_CONNECTION_STRING }}

jobs:
  test_android:
    name: Android Emulator (shard ${{ matrix.shard }})
    strategy:
      fail-fast: false
      matrix:
        shard: [1, 2]
    # use mac build for emulator hardware accelerator
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 14
    - run: npm i -g npm@8
    - run: npm ci
      env:
        DEBUG: pw:install
    - run: npm run build
    - run: npx playwright install-deps
    - name: Create Android Emulator
      run: utils/avd_recreate.sh
    - name: Start Android Emulator
      run: utils/avd_start.sh
    - name: Run tests
      run: npm run atest -- --shard=${{ matrix.shard }}/2
    - run: ./utils/upload_flakiness_dashboard.sh ./test-results/report.json
      if: always()
    - uses: actions/upload-artifact@v1
      if: ${{ always() }}
      with:
        name: android-test-results
        path: test-results

